# Generated by Django 5.2.4 on 2025-07-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.TextField(verbose_name='credito')),
                ('debito', models.TextField(verbose_name='debito')),
            ],
        ),
    ]
